translations: init danish
auxolotl/website pull request #14
Opened 2024-05-06 08:31 UTC by AngryAnt

First pass. Content complete, but I need to do another pass and a final typo check.

2024-05-06 08:55 UTC, mrshmllow requested changes

2024-05-06 08:55 UTC, mrshmllow commented on src/pages/dk/index.astro
> +<style></style>
```suggestion
---
import Layout from "../../layouts/Layout.astro";
import Home from "../../components/home/Home.astro";
---

<Layout title="auxolotl.org">
	<Home />
</Layout>```

2024-05-07 00:39 UTC, dantefromhell commented on src/i18n/ui.ts
> +import dk from "../../public/locales/dk/translations.json"
nitpick: I vote for sorting alphabetically - IMO makes finding things easier.

2024-05-07 10:41 UTC, mrshmllow approved these changes

2024-05-07 10:44 UTC, AngryAnt commented
Final pass done, typo check done, rebased on main.

Not sure who can merge - beyond tossing it at an auto-translator to verify I didn't just upload my manifest on the superiority of pygmy owls?

2024-05-07 10:45 UTC, mrshmllow commented
If you believe its done, I am happy to merge!

2024-05-07 10:45 UTC, merged